### ISSUE TITLE
Verify identity-vectors.txt

### ISSUE THREAD

**Issue by shanedk** [sqrldev/sqrl-test-vectors#1]
[identity-vectors.txt](../blob/master/vectors/identity-vectors.txt) needs to be independently verified.

**Comment by alexhauser** [comment]
Hi @shanedk,

I've just tried verifying your identity (IDK) vectors using my implementation and think I found a problem: It seems you're also using the URL's "path" in your HMAC, instead of the host part only.

For example, for a "domain" of `example.com/extended`, only `example.com` should go into the hmac according to this:
![site_keys](https://user-images.githubusercontent.com/4005543/71356312-1fefb200-2582-11ea-8bcd-48310429d796.JPG)

Only when creating the signature, the path is taken into consideration.
Am I missing something?

Best regards,
Alex

**Comment by alexhauser** [comment]
Hi again, @shanedk,

it just occured to me that you are probably simulating the "x" parameter here - sorry for not thinking about that.

With the extended path taken into account, all test vectors pass my verification just fine.

Cheers, Alex

**Comment by shanedk** [comment]
Yes, that's simulating the x-parameter. Thanks!
